# Generated by Django 2.0 on 2019-03-31 08:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddhesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('pos', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
