# Generated by Django 2.0 on 2019-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddhesh', '0002_incidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidence',
            name='locality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidence',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
