# Generated by Django 2.0 on 2019-04-10 00:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddhesh', '0004_auto_20190410_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='pos',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
